from ravshield.analyzers import (
    AnalyzerRegistry,
    BaseAnalyzer,
    ScanPipeline,
)
from ravshield.enums import Severity, Verdict
from ravshield.models import DetectionFinding


class DummyAnalyzer(BaseAnalyzer):
    """
    Simple analyzer used only for testing.
    """

    name = "dummy"

    def analyze(self, target):
        return [
            DetectionFinding(
                code="dummy_signal",
                title="Dummy Signal",
                description="Generated by dummy analyzer.",
                severity=Severity.MEDIUM,
                confidence=80,
                evidence={"target": str(target)},
            )
        ]


class EmptyAnalyzer(BaseAnalyzer):
    name = "empty"

    def analyze(self, target):
        return []


def test_pipeline_runs_registered_analyzer():
    registry = AnalyzerRegistry()

    registry.register(DummyAnalyzer())

    pipeline = ScanPipeline(registry)

    result = pipeline.analyze("example.com")

    assert result.verdict is Verdict.SUSPICIOUS
    assert len(result.findings) == 1
    assert result.analysis_modules == ["dummy"]


def test_pipeline_handles_empty_analyzer():
    registry = AnalyzerRegistry()

    registry.register(EmptyAnalyzer())

    pipeline = ScanPipeline(registry)

    result = pipeline.analyze("example.com")

    assert result.verdict is Verdict.UNKNOWN
    assert result.findings == []


def test_pipeline_runs_multiple_analyzers():
    registry = AnalyzerRegistry()

    registry.register(DummyAnalyzer())
    registry.register(EmptyAnalyzer())

    pipeline = ScanPipeline(registry)

    result = pipeline.analyze("example.com")

    assert len(result.findings) == 1

    assert result.analysis_modules == [
        "dummy",
        "empty",
    ]


def test_registry_contains_registered_analyzer():
    registry = AnalyzerRegistry()

    registry.register(DummyAnalyzer())

    assert registry.contains("dummy")


def test_registry_unregister():
    registry = AnalyzerRegistry()

    registry.register(DummyAnalyzer())

    removed = registry.unregister("dummy")

    assert removed.name == "dummy"
    assert len(registry) == 0