from __future__ import annotations

from ravshield.analyzers.base import BaseAnalyzer
from ravshield.enums import Severity
from ravshield.intel.domain import analyze_domain_heuristics
from ravshield.models import DetectionFinding


SIGNAL_CONFIG = {
    "punycode": {
        "code": "DOMAIN_PUNYCODE",
        "title": "Punycode domain detected",
        "severity": Severity.HIGH,
        "confidence": 90,
        "description": (
            "The domain uses Punycode, which may indicate an "
            "internationalized-domain homograph attack."
        ),
    },
    "suspicious_keywords": {
        "code": "DOMAIN_SUSPICIOUS_KEYWORDS",
        "title": "Suspicious domain keywords detected",
        "severity": Severity.MEDIUM,
        "confidence": 75,
        "description": (
            "The domain contains keywords commonly associated with "
            "phishing or credential theft."
        ),
    },
    "suspicious_tld": {
        "code": "DOMAIN_SUSPICIOUS_TLD",
        "title": "Suspicious top-level domain detected",
        "severity": Severity.MEDIUM,
        "confidence": 70,
        "description": (
            "The domain uses a top-level domain frequently associated "
            "with abuse or deceptive downloads."
        ),
    },
    "excessive_subdomains": {
        "code": "DOMAIN_EXCESSIVE_SUBDOMAINS",
        "title": "Excessive subdomains detected",
        "severity": Severity.LOW,
        "confidence": 60,
        "description": (
            "The domain contains an unusually deep subdomain structure."
        ),
    },
    "high_entropy": {
        "code": "DOMAIN_HIGH_ENTROPY",
        "title": "High-entropy domain detected",
        "severity": Severity.MEDIUM,
        "confidence": 70,
        "description": (
            "The domain appears unusually random and may have been "
            "generated by an automated algorithm."
        ),
    },
}


class DomainHeuristicAnalyzer(BaseAnalyzer):
    """
    Convert domain heuristic signals into detection findings.
    """

    name = "domain_heuristics"

    def analyze(
        self,
        target: str,
    ) -> list[DetectionFinding]:
        result = analyze_domain_heuristics(target)

        findings: list[DetectionFinding] = []

        for signal in result.signals:
            config = SIGNAL_CONFIG[signal]

            evidence = {
                "domain": result.domain,
                "signal": signal,
            }

            evidence.update(result.details)

            findings.append(
                DetectionFinding(
                    code=config["code"],
                    title=config["title"],
                    severity=config["severity"],
                    confidence=config["confidence"],
                    description=config["description"],
                    evidence=evidence,
                )
            )

        return findings